#include "kernel/core/interrupt/include/irq.h"
#include "drivers/interrupt/pic/pic.h"
#include <stddef.h>

// O(1) IRQ routing table mapped by interrupt vector number (32 to 255)
static irq_handler_t irq_handlers[256];

void irq_init(void) {
    for (int i = 0; i < 256; i++) {
        irq_handlers[i] = NULL;
    }

    // Register irq_dispatch with ISR Manager for vectors 32 to 255
    for (int i = 32; i < 256; i++) {
        isr_register_handler(i, irq_dispatch);
    }
}

void irq_register_handler(uint8_t irq, irq_handler_t handler) {
    // IRQs are typically 0-15, mapped to vectors 32-47
    irq_handlers[32 + irq] = handler;
    pic_clear_mask(irq); // Enable IRQ line in PIC
}

void irq_unregister_handler(uint8_t irq) {
    irq_handlers[32 + irq] = NULL;
    pic_set_mask(irq); // Disable IRQ line in PIC
}

uint64_t irq_dispatch(registers_t* regs) {
    uint64_t new_rsp = 0;
    
    // Check if we have a handler registered
    if (irq_handlers[regs->int_no] != NULL) {
        irq_handler_t handler = irq_handlers[regs->int_no];
        new_rsp = handler(regs);
    }

    // End of Interrupt (EOI) must be sent to PIC for hardware IRQs
    // Only IRQs 0-15 (vectors 32-47) are generated by the PIC.
    uint8_t irq = regs->int_no - 32;
    if (irq < 16) {
        pic_send_eoi(irq);
    }
    
    return new_rsp;
}
