#ifndef BOSPECTRA_VERSION_H
#define BOSPECTRA_VERSION_H

#define BOSPECTRA_VERSION_MAJOR 1
#define BOSPECTRA_VERSION_MINOR 0
#define BOSPECTRA_VERSION_PATCH 0
#define BOSPECTRA_VERSION_BUILD 101
#define BOSPECTRA_VERSION_TAG   "Phase1-MediaFoundation"
#define BOSPECTRA_VERSION_STR   "v1.0.0-Phase1-MediaFoundation (Build 101)"

#endif // BOSPECTRA_VERSION_H
