#ifndef BOS_SETTINGS_TYPES_H
#define BOS_SETTINGS_TYPES_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#include "userspace/libs/kernel32/include/kernel32_types.h"

typedef enum {
    SETTINGS_CATEGORY_DISPLAY = 0,
    SETTINGS_CATEGORY_APPEARANCE,
    SETTINGS_CATEGORY_PERSONALIZATION,
    SETTINGS_CATEGORY_SOUND,
    SETTINGS_CATEGORY_NETWORK,
    SETTINGS_CATEGORY_BLUETOOTH,
    SETTINGS_CATEGORY_DEVICES,
    SETTINGS_CATEGORY_STORAGE,
    SETTINGS_CATEGORY_POWER,
    SETTINGS_CATEGORY_USERS,
    SETTINGS_CATEGORY_ACCOUNTS,
    SETTINGS_CATEGORY_APPLICATIONS,
    SETTINGS_CATEGORY_PRIVACY,
    SETTINGS_CATEGORY_SECURITY,
    SETTINGS_CATEGORY_UPDATES,
    SETTINGS_CATEGORY_ACCESSIBILITY,
    SETTINGS_CATEGORY_NOTIFICATIONS,
    SETTINGS_CATEGORY_DIAGNOSTICS,
    SETTINGS_CATEGORY_ABOUT,
    SETTINGS_CATEGORY_COUNT
} SETTINGS_CATEGORY_ID;

typedef struct _SETTINGS_PAGE_INFO {
    SETTINGS_CATEGORY_ID id;
    char title[64];
    char subtitle[128];
    uint32_t icon_id;
    bool is_active;
} SETTINGS_PAGE_INFO;

#endif // BOS_SETTINGS_TYPES_H
