#ifndef BOS_VERSION_H
#define BOS_VERSION_H

#define BOS_SDK_VERSION_MAJOR 1
#define BOS_SDK_VERSION_MINOR 0
#define BOS_SDK_VERSION_PATCH 0
#define BOS_SDK_VERSION_STRING "1.0.0-PHASE4"

#define BOS_FRAMEWORK_VERSION_STRING "1.0.0-FRAMEWORK"
#define BOS_PLATFORM_VERSION_STRING "1.0.0-PLATFORM"
#define BOS_MIN_SUPPORTED_KERNEL_VERSION "0.9.8"

#endif /* BOS_VERSION_H */
