; Auto-generated by generate_boot_assets.py
section .rodata

global g_boot_ico_lock_png
global g_boot_ico_ethernet_png
global g_boot_ico_chat_png
global g_boot_ico_user_png
global g_boot_wallpaper_qoi_0
global g_boot_wallpaper_qoi

g_boot_ico_lock_png:
    incbin 'BOOT(OS-ICO)/lock.png'

g_boot_ico_ethernet_png:
    incbin 'BOOT(OS-ICO)/ethernet-port.png'

g_boot_ico_chat_png:
    incbin 'BOOT(OS-ICO)/chat.png'

g_boot_ico_user_png:
    incbin 'BOOT(OS-ICO)/user.png'

g_boot_wallpaper_qoi_0:
    incbin 'build/wallpapers/wp_0.qoi'

g_boot_wallpaper_qoi:
    incbin 'build/wallpapers/wp_0.qoi'

