/* AUTO-GENERATED BY tools/generate_bofont.py — DO NOT HAND EDIT */
#ifndef KERNEL_BOFONT_ASSETS_H
#define KERNEL_BOFONT_ASSETS_H

#include "font_types.h"

extern const BOFontAsset g_bofont_asset_ui_regular;
extern const BOFontAsset g_bofont_asset_ui_medium;
extern const BOFontAsset g_bofont_asset_ui_bold;
extern const BOFontAsset g_bofont_asset_caption;
extern const BOFontAsset g_bofont_asset_title;
extern const BOFontAsset g_bofont_asset_mono;

#endif // KERNEL_BOFONT_ASSETS_H
