/**
 * @file bdce_types.h
 * @brief ATOMS OS BDCE (BOS Display Contract Engine) - Core Type & State Definitions
 * @note Phase A — Architectural Foundation Only. Zero algorithms or rendering logic.
 */

#ifndef ATOMS_OS_BDCE_TYPES_H
#define ATOMS_OS_BDCE_TYPES_H

#include <stdint.h>
#include <stdbool.h>

/* Maximum number of dirty rectangles tracked per damage state */
#define BDCE_MAX_DIRTY_REGIONS  64

/**
 * @brief Universal 2D rectangle structure used across BDCE State pillars
 */
typedef struct {
    int32_t x;
    int32_t y;
    uint32_t width;
    uint32_t height;
} BDCE_Rect;

/**
 * @brief Pillar 1: Physical State (`BDCE_PhysicalState`)
 * Authoritative ground truth of the hardware scanout framebuffer device.
 */
typedef struct {
    uint32_t display_id;            /* Unique hardware display identifier */
    uint32_t physical_width;        /* Physical scanout width in pixels (e.g., 1920) */
    uint32_t physical_height;       /* Physical scanout height in pixels (e.g., 1080) */
    uint32_t hardware_pitch_bytes;  /* Physical scanline byte-stride (e.g., 7680) */
    uint32_t bytes_per_pixel;       /* Bytes per pixel (e.g., 4 for ARGB32) */
    uint32_t refresh_rate_hz;       /* Hardware scanout refresh rate (e.g., 60Hz) */
    uint64_t vram_base_paddr;       /* Physical VRAM base address */
    uint64_t vram_size_bytes;       /* Total VRAM aperture size in bytes */
} BDCE_PhysicalState;

/**
 * @brief Pillar 2: Logical State (`BDCE_LogicalState`)
 * Desktop geometry, scaling, and safe-area boundaries negotiated by policy/layout.
 */
typedef struct {
    uint32_t logical_width;         /* Logical desktop width in pixels (e.g., 1280) */
    uint32_t logical_height;        /* Logical desktop height in pixels (e.g., 720) */
    uint32_t scale_factor_pct;      /* DPI scaling percentage (e.g., 100 or 150) */
    BDCE_Rect safe_area_rect;       /* Guaranteed visible safe region */
    BDCE_Rect desktop_work_area;    /* Region outside taskbar and system docks */
} BDCE_LogicalState;

/**
 * @brief Pillar 3: Surface State (`BDCE_SurfaceState`)
 * Structural definition of any memory canvas, replacing loose pointers with opaque handles.
 */
typedef struct {
    uint32_t surface_id;            /* Unique surface handle ID */
    uint32_t width;                 /* Surface width in pixels */
    uint32_t height;                /* Surface height in pixels */
    uint32_t pitch_bytes;           /* Explicit byte-stride (never derived via width * 4) */
    void*    virtual_address;       /* Kernel virtual address of pixel buffer */
} BDCE_SurfaceState;

/**
 * @brief Pillar 4: Temporal State (`BDCE_TemporalState`)
 * Epochs, VBlank pacing, and synchronization state across presentation timelines.
 */
typedef struct {
    uint64_t display_epoch_id;      /* Incremented on hotplug, resolution change, or reset */
    uint64_t current_vblank_count;  /* Monotonically increasing VBlank interrupt counter */
    uint64_t last_vblank_timestamp; /* Microsecond timestamp of the last VBlank */
    uint64_t presentation_fence_id; /* Hardware or software synchronization fence token */
    uint32_t active_vram_page;      /* Currently active hardware CRTC scanout page index */
} BDCE_TemporalState;

/**
 * @brief Pillar 5: Frame State (`BDCE_FrameState`)
 * Lifecycle tracking of active rendering frames to prevent use-after-free anomalies.
 */
typedef enum {
    BDCE_FRAME_PENDING = 0,         /* Frame is actively being generated by producer */
    BDCE_FRAME_COMPOSITED,          /* Frame composition completed by BWE */
    BDCE_FRAME_QUEUED,              /* Frame enqueued in AGDTE presentation timeline */
    BDCE_FRAME_PRESENTED,           /* Frame successfully flipped/blitted to scanout */
    BDCE_FRAME_DROPPED              /* Frame dropped due to pacing or invalidation */
} BDCE_FrameLifecycleStatus;

typedef struct {
    uint64_t frame_sequence_id;     /* Monotonically increasing frame sequence number */
    uint64_t start_timestamp_us;    /* Frame generation timestamp */
    uint32_t dirty_rect_count;      /* Number of dirty regions recorded during this frame */
    BDCE_FrameLifecycleStatus lifecycle_state; /* Active lifecycle state */
} BDCE_FrameState;

/**
 * @brief Pillar 6: Presentation State (`BDCE_PresentationState`)
 * Bridge translation instructions between logical surfaces and physical VRAM backpages.
 */
typedef struct {
    uint32_t source_surface_id;     /* Source composition surface ID (e.g., BWE RAM target) */
    uint32_t destination_surface_id;/* Destination VRAM backpage surface ID (Page 1) */
    bool     requires_scaling;      /* True if Source dimensions != Destination dimensions */
    bool     requires_format_conv;  /* True if pixel format conversion is required */
    uint32_t target_vram_page_idx;  /* Target hardware VRAM page index */
    uint64_t target_vblank_us;      /* Target execution VSync timestamp in microseconds */
} BDCE_PresentationState;

/**
 * @brief Pillar 7: Damage State (`BDCE_DamageState`)
 * Authoritative registry of modified screen regions to prevent duplicate tracking arrays.
 */
typedef struct {
    uint32_t  region_count;         /* Number of active dirty rectangles */
    BDCE_Rect dirty_boxes[BDCE_MAX_DIRTY_REGIONS]; /* Array of dirty bounding boxes */
    BDCE_Rect bounding_union;       /* Single bounding rectangle enclosing all dirty boxes */
    uint32_t  age_frames;           /* Frames elapsed since this damage state was updated */
} BDCE_DamageState;

/**
 * @brief Pillar 8: Ownership State (`BDCE_OwnershipState`)
 * Concurrency mutex tracking exactly which subsystem holds read/write rights to a surface.
 */
typedef enum {
    BDCE_OWNER_FREE = 0,            /* Unallocated / surface pool available */
    BDCE_OWNER_COMPOSITOR_BWE,      /* Owned by BWE — Actively writing UI pixels */
    BDCE_OWNER_WALLPAPER_ENGINE,    /* Owned by Wallpaper — Actively decoding background */
    BDCE_OWNER_SCHEDULER_AGDTE,     /* Owned by AGDTE — Enqueued in presentation queue */
    BDCE_OWNER_BLITTER_BSPE,        /* Owned by BSPE — Actively blitting to VRAM */
    BDCE_OWNER_HARDWARE_SCANOUT     /* Owned by VBE/CRTC — Currently on scanout display */
} BDCE_OwnershipState;

/**
 * @brief Pillar 9: Capability State (`BDCE_CapabilityState`)
 * Hardware capabilities queried by DIE/AGDAE before policy decisions are made.
 */
typedef struct {
    bool can_hardware_scale;        /* True if hardware/GPU scaling is supported */
    bool can_hardware_flip;         /* True if CRTC register page flipping is supported */
    bool can_hardware_cursor;       /* True if hardware cursor overlay plane is supported */
    bool can_triple_buffer;         /* True if 3 physical VRAM pages are supported */
    bool supports_hdr_10bit;        /* True if 10-bit ARGB2101010 format is supported */
} BDCE_CapabilityState;

#endif /* ATOMS_OS_BDCE_TYPES_H */
