/**
 * @file bdce_validation.h
 * @brief ATOMS OS BDCE (BOS Display Contract Engine) - Read-Only Validation Layer (`Constitutional Observation`)
 * @note Phase C — Constitutional Observation Layer. Strictly read-only validation (`DO NOT FIX / NEVER REPAIR`).
 */

#ifndef ATOMS_OS_BDCE_VALIDATION_H
#define ATOMS_OS_BDCE_VALIDATION_H

#include "bdce_types.h"
#include "bdce_context.h"

/* ========================================================================== */
/* Validation Status & Report Structures (`Read-Only Observation Layer`)      */
/* ========================================================================== */

typedef enum {
    BDCE_VALIDATION_PASS = 0,
    BDCE_VALIDATION_FAIL = 1,
    BDCE_VALIDATION_WARN = 2,
    BDCE_VALIDATION_UNKNOWN = 3
} BDCE_ValidationStatus;

/**
 * @brief Comprehensive Observation Report for the 5 Constitutional Pillars.
 */
typedef struct {
    BDCE_ValidationStatus physical_status;
    BDCE_ValidationStatus logical_status;
    BDCE_ValidationStatus surface_status;
    BDCE_ValidationStatus capability_status;
    BDCE_ValidationStatus temporal_status;

    uint32_t total_checks_performed;
    uint32_t checks_passed;
    uint32_t checks_failed;
    uint32_t checks_warned;

    /* Discrepancy Recording (Strictly observed values vs authority state — DO NOT FIX) */
    uint32_t expected_physical_width;
    uint32_t observed_physical_width;
    uint32_t expected_physical_height;
    uint32_t observed_physical_height;
    uint32_t expected_pitch_bytes;
    uint32_t observed_pitch_bytes;

    uint32_t expected_logical_width;
    uint32_t observed_logical_width;
    uint32_t expected_logical_height;
    uint32_t observed_logical_height;
} BDCE_ValidationReport;

/* ========================================================================== */
/* Public Validation APIs (`Passive Observers — Zero Mutations/Algorithms`)  */
/* ========================================================================== */

/**
 * @brief Performs read-only constitutional observation and verification across all display states.
 * @note Strictly read-only. Zero mutations, zero algorithm overrides, zero repairs.
 * @param boot_info Pointer to multiboot boot_info_t struct (const void* to avoid circular header dependencies).
 * @param hw_fb Pointer to hardware framebuffer BVFramebuffer (const void* to avoid circular header dependencies).
 * @param out_report Pointer to receive the structured validation report.
 * @return true if all constitutional pillars PASS without discrepancy, false if a discrepancy is observed.
 */
bool BDCE_ValidateCurrentSystem(const void* boot_info, const void* hw_fb, BDCE_ValidationReport* out_report);

/**
 * @brief Outputs the structured BDCE Validation Report to diagnostic/console channels.
 * @param report Pointer to the report generated by BDCE_ValidateCurrentSystem.
 */
void BDCE_DumpValidationReport(const BDCE_ValidationReport* report);

#endif /* ATOMS_OS_BDCE_VALIDATION_H */
