#include "studio/include/studio_designer.h"
#include "kernel/core/lib/include/string.h"

BOS_Result BOS_Studio_SerializeForm(const BOS_StudioForm* form, char* out_buf, size_t max_buf) {
    if (!form || !out_buf || max_buf < 128) return BOS_ERROR_INVALID_ARGUMENT;

    /* Simple JSON serialization stub */
    strncpy(out_buf, "{\n  \"form\": \"MainWindow\",\n  \"controls\": []\n}\n", max_buf - 1);
    out_buf[max_buf - 1] = '\0';
    return BOS_SUCCESS;
}

BOS_Result BOS_Studio_GenerateCppCode(const BOS_StudioForm* form, char* out_code_buf, size_t max_buf) {
    if (!form || !out_code_buf || max_buf < 256) return BOS_ERROR_INVALID_ARGUMENT;

    strncpy(out_code_buf, 
        "// Generated by BOS Studio Form Serializer — DO NOT EDIT DIRECTLY\n"
        "#pragma once\n"
        "#include <bosui/bosui.hpp>\n\n"
        "class MainWindowDesign {\n"
        "public:\n"
        "    bosui::Window window{\"MainWindow\", 640, 480};\n"
        "    void InitializeComponent() {\n"
        "        window.Show();\n"
        "    }\n"
        "};\n", max_buf - 1);

    out_code_buf[max_buf - 1] = '\0';
    return BOS_SUCCESS;
}
