#!/usr/bin/env python3
"""
ATOMS OS — Host Code Generator for GN/Ninja Build Verification
Copyright © 2026 ATOMS OS Project / Saumya Chaudhari
Generates C source metadata during the build action phase.
"""

import sys
import argparse
import time

def main():
    parser = argparse.ArgumentParser(description="ATOMS GN Code Generator")
    parser.add_argument("--out", required=True, help="Output C source file path")
    args = parser.parse_args()

    content = f"""/* Generated by ATOMS Host Code Generator */
#include "userspace/runtime/c/include/stdio.h"

const char* atoms_get_build_timestamp(void) {{
    return "{time.strftime('%Y-%m-%d %H:%M:%S')}";
}}

const char* atoms_get_toolchain_name(void) {{
    return "ATOMS GN+Ninja+Clang Host Generator Pipeline";
}}

void atoms_print_generated_info(void) {{
    printf("[CODEGEN_ACTION] Timestamp: %s | Pipeline: %s\\n",
           atoms_get_build_timestamp(), atoms_get_toolchain_name());
}}
"""
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(content)
    
    print(f"[CODEGEN] Generated {args.out} successfully.")
    return 0

if __name__ == "__main__":
    sys.exit(main())
