import os

files = [
    ('ObjectTest', r'D:\Signatures_OS\test_phase5\ObjectTest.class'),
    ('StringTest', r'D:\Signatures_OS\test_phase5\StringTest.class'),
    ('WrapperTest', r'D:\Signatures_OS\test_phase5\WrapperTest.class'),
    ('CollectionsSafetyTest', r'D:\Signatures_OS\test_phase5\CollectionsSafetyTest.class'),
    ('MemoryPressureTest', r'D:\Signatures_OS\test_phase5\MemoryPressureTest.class'),
    ('ArgTest', r'D:\Signatures_OS\test_phase5\ArgTest.class'),
    ('DemoApp', r'D:\Signatures_OS\test_phase5\com\atoms\demo\App.class'),
    ('DemoConfig', r'D:\Signatures_OS\test_phase5\com\atoms\demo\Config.class'),
    ('DemoUtils', r'D:\Signatures_OS\test_phase5\com\atoms\demo\Utils.class'),
    ('DemoMainP5', r'D:\Signatures_OS\test_phase5\com\atoms\demo\Main.class'),
    ('DemoJarP5', r'D:\Signatures_OS\test_phase5\demo.jar'),
    ('DemoJarCompressed', r'D:\Signatures_OS\test_phase5\demo_compressed.jar'),
    ('ConfigFile', r'D:\Signatures_OS\test_phase5\jar_staging\config.txt'),
]

out = []
out.append("/*")
out.append(" * ATOMS OS — Embedded Bytecode & JAR Test Assets for Phase 5")
out.append(" * Auto-generated by build tooling")
out.append(" */")
out.append("#pragma once")
out.append("#include <stdint.h>")
out.append("#include <stddef.h>")
out.append("")

for name, path in files:
    with open(path, "rb") as f:
        data = f.read()
    hex_strs = [f"0x{b:02x}" for b in data]
    lines = []
    for i in range(0, len(hex_strs), 16):
        lines.append("  " + ", ".join(hex_strs[i:i+16]))
    body = ",\n".join(lines)
    out.append(f"static const uint8_t k{name}Data[] = {{\n{body}\n}};")
    out.append(f"static const size_t k{name}Length = {len(data)};")
    out.append("")

with open(r"D:\Signatures_OS\userspace\apps\java\phase5_test_assets.h", "w", encoding="utf-8") as f:
    f.write("\n".join(out))

print("phase5_test_assets.h written successfully!")
