import os

files = [
    ('ExceptionTest', r'D:\Signatures_OS\test_phase4\ExceptionTest.class'),
    ('Greeter', r'D:\Signatures_OS\test_phase4\Greeter.class'),
    ('MultiClassTest', r'D:\Signatures_OS\test_phase4\MultiClassTest.class'),
    ('DemoMain', r'D:\Signatures_OS\test_phase4\com\atoms\demo\Main.class'),
    ('UtilTest', r'D:\Signatures_OS\test_phase4\UtilTest.class'),
    ('UncaughtCrashTest', r'D:\Signatures_OS\test_phase4\UncaughtCrashTest.class'),
    ('DemoJar', r'D:\Signatures_OS\test_phase4\demo.jar'),
]

out = []
out.append("/*")
out.append(" * ATOMS OS — Embedded Bytecode & JAR Test Assets for Phase 4")
out.append(" * Auto-generated by build tooling")
out.append(" */")
out.append("#pragma once")
out.append("#include <stdint.h>")
out.append("#include <stddef.h>")
out.append("")

for name, path in files:
    with open(path, "rb") as f:
        data = f.read()
    hex_strs = [f"0x{b:02x}" for b in data]
    lines = []
    for i in range(0, len(hex_strs), 16):
        lines.append("  " + ", ".join(hex_strs[i:i+16]))
    body = ",\n".join(lines)
    out.append(f"static const uint8_t k{name}Data[] = {{\n{body}\n}};")
    out.append(f"static const size_t k{name}Length = {len(data)};")
    out.append("")

with open(r"D:\Signatures_OS\userspace\apps\java\phase4_test_assets.h", "w", encoding="utf-8") as f:
    f.write("\n".join(out))

print("phase4_test_assets.h written successfully!")
