"""
ATOMS OS — Inter Font Asset Generator (Phase 4A)
Rasterizes licensed Inter TTF fonts into compact, offline C++ and C alpha glyph tables.
License: SIL Open Font License 1.1 (Rasmus Andersson)
"""

import os
from PIL import Image, ImageFont, ImageDraw

FONT_DIR = os.path.abspath("third_party/fonts/inter")
OUTPUT_HEADER_CPP = os.path.join(FONT_DIR, "inter_font_data.hpp")
OUTPUT_HEADER_C   = os.path.join(FONT_DIR, "inter_font_c.h")

CONFIGS = [
    {
        "symbol": "g_font_inter_regular_13",
        "family": "Inter",
        "weight": "bos::FontWeight::Regular",
        "ttf": os.path.join(FONT_DIR, "Inter-Regular.ttf"),
        "size": 13,
        "line_height": 17,
        "var_prefix": "g_inter_reg13"
    },
    {
        "symbol": "g_font_inter_bold_13",
        "family": "Inter",
        "weight": "bos::FontWeight::Bold",
        "ttf": os.path.join(FONT_DIR, "Inter-Bold.ttf"),
        "size": 13,
        "line_height": 17,
        "var_prefix": "g_inter_bold13"
    },
    {
        "symbol": "g_font_inter_title_18",
        "family": "Inter",
        "weight": "bos::FontWeight::Bold",
        "ttf": os.path.join(FONT_DIR, "Inter-Bold.ttf"),
        "size": 18,
        "line_height": 24,
        "var_prefix": "g_inter_title18"
    },
    {
        "symbol": "g_font_inter_caption_11",
        "family": "Inter",
        "weight": "bos::FontWeight::Regular",
        "ttf": os.path.join(FONT_DIR, "Inter-Regular.ttf"),
        "size": 11,
        "line_height": 15,
        "var_prefix": "g_inter_caption11"
    }
]

def generate():
    os.makedirs(FONT_DIR, exist_ok=True)

    # Process all configs
    parsed_fonts = []
    for cfg in CONFIGS:
        font = ImageFont.truetype(cfg["ttf"], cfg["size"])
        ascent, descent = font.getmetrics()
        line_height = cfg["line_height"]
        var_prefix = cfg["var_prefix"]

        alpha_bytes = bytearray()
        glyphs = []

        for cp in range(32, 127):
            c = chr(cp)
            adv = int(round(font.getlength(c)))
            if adv < 0: adv = 0

            # Render glyph with baseline origin at (20, 30)
            img = Image.new('L', (60, 60), 0)
            draw = ImageDraw.Draw(img)
            draw.text((20, 30), c, font=font, fill=255, anchor='ls')
            bbox = img.getbbox()

            if bbox and cp != 32:
                bx = bbox[0] - 20
                by = bbox[1] - 30
                w = bbox[2] - bbox[0]
                h = bbox[3] - bbox[1]
                offset = len(alpha_bytes)

                crop = img.crop(bbox)
                glyph_raw = crop.tobytes()
                alpha_bytes.extend(glyph_raw)

                glyphs.append({
                    "cp": cp,
                    "adv": adv,
                    "bx": bx,
                    "by": by,
                    "w": w,
                    "h": h,
                    "offset": offset
                })
            else:
                glyphs.append({
                    "cp": cp,
                    "adv": adv,
                    "bx": 0,
                    "by": 0,
                    "w": 0,
                    "h": 0,
                    "offset": 0
                })

        parsed_fonts.append({
            "cfg": cfg,
            "ascent": ascent,
            "descent": descent,
            "line_height": line_height,
            "alpha_bytes": alpha_bytes,
            "glyphs": glyphs
        })
        print(f"Rasterized {cfg['symbol']}: {len(glyphs)} glyphs, {len(alpha_bytes)} alpha bytes, ascent={ascent}, descent={descent}")

    # =========================================================================
    # 1. EMIT C++ HEADER (inter_font_data.hpp)
    # =========================================================================
    out_cpp = []
    out_cpp.append("// AUTO-GENERATED BY tools/generate_inter_assets.py — DO NOT HAND EDIT")
    out_cpp.append("// Source: Inter Font (SIL Open Font License 1.1 by Rasmus Andersson)")
    out_cpp.append("#ifndef THIRD_PARTY_FONTS_INTER_FONT_DATA_HPP")
    out_cpp.append("#define THIRD_PARTY_FONTS_INTER_FONT_DATA_HPP\n")
    out_cpp.append("#include \"bos/font.hpp\"\n")
    out_cpp.append("namespace bos { namespace font_data {\n")

    for pf in parsed_fonts:
        cfg = pf["cfg"]
        var_prefix = cfg["var_prefix"]
        alpha_bytes = pf["alpha_bytes"]
        glyphs = pf["glyphs"]

        # Emit Alpha Array
        out_cpp.append(f"static const uint8_t {var_prefix}_alpha[{len(alpha_bytes)}] = {{")
        for i in range(0, len(alpha_bytes), 16):
            chunk = alpha_bytes[i:i+16]
            hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
            out_cpp.append(f"    {hex_str},")
        out_cpp.append("};\n")

        # Emit Glyphs Array
        out_cpp.append(f"static const bos::GlyphData {var_prefix}_glyphs[95] = {{")
        for g in glyphs:
            out_cpp.append(f"    {{ {g['cp']}, {g['adv']}, {g['bx']}, {g['by']}, {g['w']}, {g['h']}, {g['offset']} }},")
        out_cpp.append("};\n")

        # Emit FontAsset Struct
        out_cpp.append(f"static const bos::FontAsset {cfg['symbol']} = {{")
        out_cpp.append(f"    \"{cfg['family']}\",")
        out_cpp.append(f"    {cfg['weight']},")
        out_cpp.append(f"    {cfg['size']},")
        out_cpp.append(f"    {pf['line_height']},")
        out_cpp.append(f"    {pf['ascent']},")
        out_cpp.append(f"    {pf['descent']},")
        out_cpp.append(f"    {var_prefix}_glyphs,")
        out_cpp.append(f"    {var_prefix}_alpha,")
        out_cpp.append(f"    sizeof({var_prefix}_alpha)")
        out_cpp.append("};\n")

    out_cpp.append("}} // namespace bos::font_data\n")
    out_cpp.append("#endif // THIRD_PARTY_FONTS_INTER_FONT_DATA_HPP\n")

    with open(OUTPUT_HEADER_CPP, "w", encoding="utf-8") as f:
        f.write("\n".join(out_cpp))
    print(f"Successfully wrote {OUTPUT_HEADER_CPP}")

    # =========================================================================
    # 2. EMIT C COMPATIBLE HEADER (inter_font_c.h)
    # =========================================================================
    out_c = []
    out_c.append("// AUTO-GENERATED BY tools/generate_inter_assets.py — DO NOT HAND EDIT")
    out_c.append("// Source: Inter Font (SIL Open Font License 1.1 by Rasmus Andersson)")
    out_c.append("#ifndef THIRD_PARTY_FONTS_INTER_FONT_C_H")
    out_c.append("#define THIRD_PARTY_FONTS_INTER_FONT_C_H\n")
    out_c.append("#include <stdint.h>")
    out_c.append("#include <stddef.h>")
    out_c.append("#include <stdbool.h>\n")
    out_c.append("typedef struct {")
    out_c.append("    uint8_t  codepoint;")
    out_c.append("    int8_t   advance_x;")
    out_c.append("    int8_t   bearing_x;")
    out_c.append("    int8_t   bearing_y;")
    out_c.append("    uint8_t  width;")
    out_c.append("    uint8_t  height;")
    out_c.append("    uint32_t alpha_offset;")
    out_c.append("} inter_glyph_t;\n")
    out_c.append("typedef struct {")
    out_c.append("    const char* family;")
    out_c.append("    uint8_t     size;")
    out_c.append("    uint8_t     line_height;")
    out_c.append("    int8_t      ascent;")
    out_c.append("    int8_t      descent;")
    out_c.append("    const inter_glyph_t* glyphs;")
    out_c.append("    const uint8_t*       alpha;")
    out_c.append("    size_t               alpha_size;")
    out_c.append("} inter_font_t;\n")
    out_c.append("enum {")
    out_c.append("    INTER_FONT_REGULAR = 0,")
    out_c.append("    INTER_FONT_BOLD    = 1,")
    out_c.append("    INTER_FONT_TITLE   = 2,")
    out_c.append("    INTER_FONT_CAPTION = 3")
    out_c.append("};\n")

    for pf in parsed_fonts:
        cfg = pf["cfg"]
        var_prefix = cfg["var_prefix"]
        alpha_bytes = pf["alpha_bytes"]
        glyphs = pf["glyphs"]

        out_c.append(f"static const uint8_t {var_prefix}_c_alpha[{len(alpha_bytes)}] = {{")
        for i in range(0, len(alpha_bytes), 16):
            chunk = alpha_bytes[i:i+16]
            hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
            out_c.append(f"    {hex_str},")
        out_c.append("};\n")

        out_c.append(f"static const inter_glyph_t {var_prefix}_c_glyphs[95] = {{")
        for g in glyphs:
            out_c.append(f"    {{ {g['cp']}, {g['adv']}, {g['bx']}, {g['by']}, {g['w']}, {g['h']}, {g['offset']} }},")
        out_c.append("};\n")

    out_c.append("static const inter_font_t g_inter_c_fonts[4] = {")
    out_c.append(f"    {{ \"Inter\", 13, 17, {parsed_fonts[0]['ascent']}, {parsed_fonts[0]['descent']}, g_inter_reg13_c_glyphs, g_inter_reg13_c_alpha, sizeof(g_inter_reg13_c_alpha) }},")
    out_c.append(f"    {{ \"Inter\", 13, 17, {parsed_fonts[1]['ascent']}, {parsed_fonts[1]['descent']}, g_inter_bold13_c_glyphs, g_inter_bold13_c_alpha, sizeof(g_inter_bold13_c_alpha) }},")
    out_c.append(f"    {{ \"Inter\", 18, 24, {parsed_fonts[2]['ascent']}, {parsed_fonts[2]['descent']}, g_inter_title18_c_glyphs, g_inter_title18_c_alpha, sizeof(g_inter_title18_c_alpha) }},")
    out_c.append(f"    {{ \"Inter\", 11, 15, {parsed_fonts[3]['ascent']}, {parsed_fonts[3]['descent']}, g_inter_caption11_c_glyphs, g_inter_caption11_c_alpha, sizeof(g_inter_caption11_c_alpha) }}")
    out_c.append("};\n")

    # Helper rendering functions
    out_c.append("""static inline void draw_inter_text(uint32_t* fb, uint32_t stride, const char* str, int x, int y, uint32_t color, int font_id) {
    if (!fb || !str || !*str) return;
    if (font_id < 0 || font_id > 3) font_id = 0;
    const inter_font_t* font = &g_inter_c_fonts[font_id];
    int cur_x = x;
    int baseline_y = y + font->ascent;

    while (*str) {
        char c = *str++;
        if (c < 32 || c > 126) {
            cur_x += 7;
            continue;
        }
        const inter_glyph_t* g = &font->glyphs[c - 32];
        if (g->width > 0 && g->height > 0) {
            int gx = cur_x + g->bearing_x;
            int gy = baseline_y + g->bearing_y;
            const uint8_t* bmp = &font->alpha[g->alpha_offset];
            for (uint32_t row = 0; row < g->height; row++) {
                int py = gy + row;
                for (uint32_t col = 0; col < g->width; col++) {
                    int px = gx + col;
                    uint8_t alpha = bmp[row * g->width + col];
                    if (alpha > 0) {
                        uint32_t bg = fb[py * stride + px];
                        uint32_t inv_a = 255 - alpha;
                        uint32_t r = (((color >> 16) & 0xFF) * alpha + ((bg >> 16) & 0xFF) * inv_a) >> 8;
                        uint32_t g_c = (((color >> 8) & 0xFF) * alpha + ((bg >> 8) & 0xFF) * inv_a) >> 8;
                        uint32_t b = ((color & 0xFF) * alpha + (bg & 0xFF) * inv_a) >> 8;
                        fb[py * stride + px] = 0xFF000000 | (r << 16) | (g_c << 8) | b;
                    }
                }
            }
        }
        cur_x += g->advance_x;
    }
}

static inline int measure_inter_text(const char* str, int font_id) {
    if (!str) return 0;
    if (font_id < 0 || font_id > 3) font_id = 0;
    const inter_font_t* font = &g_inter_c_fonts[font_id];
    int w = 0;
    while (*str) {
        char c = *str++;
        if (c >= 32 && c <= 126) {
            w += font->glyphs[c - 32].advance_x;
        } else {
            w += 7;
        }
    }
    return w;
}

static inline void draw_inter_text_centered(uint32_t* fb, uint32_t stride, const char* str, int x, int y, int w, int h, uint32_t color, int font_id) {
    int tw = measure_inter_text(str, font_id);
    const inter_font_t* font = &g_inter_c_fonts[font_id];
    int tx = x + (w - tw) / 2;
    int ty = y + (h - font->line_height) / 2;
    draw_inter_text(fb, stride, str, tx, ty, color, font_id);
}
""")
    out_c.append("#endif // THIRD_PARTY_FONTS_INTER_FONT_C_H\n")

    with open(OUTPUT_HEADER_C, "w", encoding="utf-8") as f:
        f.write("\n".join(out_c))
    print(f"Successfully wrote {OUTPUT_HEADER_C}")

if __name__ == "__main__":
    generate()
